### Get /
GET {{ploufbag_api_base_url}}/
Cookie: sid={{jwt}};
Content-Type: application/json

### Get /activities
GET {{ploufbag_api_base_url}}/activities
Cookie: sid={{jwt}};
Content-Type: application/json

### Generate token
GET {{ploufbag_api_base_url}}/token?pilot_id=4142500
Cookie: sid={{jwt}};
Content-Type: application/json

### Get /takeoff/[slug]
GET {{ploufbag_api_base_url}}/takeoff/123
Content-Type: application/json
