### Hello functions
POST {{ploufbag_tasks_base_url}}
Content-Type: application/json

{
  "name": "HelloWorld",
  "hello": "World"
}




### FetchAllActivities
POST {{ploufbag_tasks_base_url}}
Content-Type: application/json

{
  "name": "FetchAllActivities",
  "pilotId": 4142500
}

### SyncSites
POST {{ploufbag_tasks_base_url}}
Content-Type: application/json

{
  "name": "SyncSites"
}

### UpdateDescription
POST {{ploufbag_tasks_base_url}}
Content-Type: application/json

{
  "name": "UpdateDescription",
  "flightId": 15565959233
}