services:
  site:
    container_name: site
    build:
      context: .
      dockerfile: site/dev.Dockerfile
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_HOST=${LOCAL_DATABASE_HOST}
      - DATABASE_USER=${LOCAL_DATABASE_USER}
      - DATABASE_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - DATABASE_NAME=${LOCAL_DATABASE_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - API_URL=${API_URL}
      - TASKS_URL=${TASKS_URL}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
    volumes:
      - ./site/src:/app/src
      - ./site/public:/app/public
      - ./common:/app/common
      - next-cache:/app/.next
    restart: always
    ports:
      - ${SITE_PORT}:3000

  tasks:
    container_name: tasks
    build:
      context: .
      dockerfile: functions/dev.Dockerfile
    environment:
      - TASKS_PORT=${TASKS_PORT}
      - DATABASE_HOST=${LOCAL_DATABASE_HOST}
      - DATABASE_USER=${LOCAL_DATABASE_USER}
      - DATABASE_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - DATABASE_NAME=${LOCAL_DATABASE_NAME}
      - FFVL_KEY=${FFVL_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ./functions/src:/app/src
      - ./common:/app/common
    expose:
      - '${TASKS_PORT}'
    ports:
      - ${TASKS_PORT}:${TASKS_PORT}
    command: yarn devTasks

  webhooks:
    container_name: webhooks
    build:
      context: .
      dockerfile: functions/dev.Dockerfile
    environment:
      - WEBHOOKS_PORT=${WEBHOOKS_PORT}
      - DATABASE_HOST=${LOCAL_DATABASE_HOST}
      - DATABASE_USER=${LOCAL_DATABASE_USER}
      - DATABASE_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - DATABASE_NAME=${LOCAL_DATABASE_NAME}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - SITE_URL=${SITE_URL}
    volumes:
      - ./functions/src:/app/src
    expose:
      - '${WEBHOOKS_PORT}'
    ports:
      - ${WEBHOOKS_PORT}:${WEBHOOKS_PORT}
    command: yarn devWebhooks

  api:
    container_name: api
    restart: no
    build:
      context: .
      dockerfile: functions/dev.Dockerfile
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_HOST=${LOCAL_DATABASE_HOST}
      - DATABASE_USER=${LOCAL_DATABASE_USER}
      - DATABASE_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - DATABASE_NAME=${LOCAL_DATABASE_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ./functions/src:/app/src
    expose:
      - '${API_PORT}'
    ports:
      - ${API_PORT}:${API_PORT}
    command: yarn devApi

  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=${LOCAL_DATABASE_USER}
      - POSTGRES_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - POSTGRES_DB=${LOCAL_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data/

volumes:
  database:
  next-cache:
